# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeve < Formula
  desc ""
  homepage "https://github.com/a0xAi/kubeve"
  version "0.3.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.10/kubeve_Darwin_x86_64.tar.gz"
      sha256 "738122ce0d57e9e94cf22c3ace8ad4135b831b22d82006d1b35c3a8bfa2964ae"

      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.10/kubeve_Darwin_arm64.tar.gz"
      sha256 "ac7267967557ac5eacde8bf154f39ee19bb16a7b03acd5c6ae17b772eaa82e0a"

      def install
        bin.install "kubeve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.10/kubeve_Linux_x86_64.tar.gz"
      sha256 "5d49dc76b5c733f9f2f0dca741cf6c8d5de6efb2c8007869c4d9a2dbdda7ecd8"
      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.10/kubeve_Linux_arm64.tar.gz"
      sha256 "bfd1369e0734bede97f0a734a8a9866dcc68d0e99bcb1536071f21ccde0f5da9"
      def install
        bin.install "kubeve"
      end
    end
  end
end
