# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeve < Formula
  desc ""
  homepage "https://github.com/a0xAi/kubeve"
  version "0.3.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.11/kubeve_Darwin_x86_64.tar.gz"
      sha256 "10ceb63c8c15804a1b84016f6a2bef9f79c4494f4792d402e468c05c97e543b5"

      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.11/kubeve_Darwin_arm64.tar.gz"
      sha256 "9bb8f09d3009d5dbfa9dee06b0d1302c2e8d0c7f25971408132c7655eaddbe35"

      def install
        bin.install "kubeve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.11/kubeve_Linux_x86_64.tar.gz"
      sha256 "a5f2bfdab32c33e93bb9ea624e6b3dadbdc243668fafc672446e1e4c886e6a66"
      def install
        bin.install "kubeve"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/a0xAi/kubeve/releases/download/v0.3.11/kubeve_Linux_arm64.tar.gz"
      sha256 "545ef3ed1a38f480e47ace56b562bfbc1ca017d6398b834c41f239702c305950"
      def install
        bin.install "kubeve"
      end
    end
  end
end
